apps:
  # map the environments to your desired heroku app names
  # for example,
  #   production: awesomeapp
  # would create the RACK_ENV=production
  # and deploy to http://awesomeapp.heroku.com
  production: recoverytracker
  staging: recoverytracker-staging
  # legacy: awesomeapp-legacy

stacks:
  # choose the stacks you want to use for each app.
  # the all: setting sets the default
  all: cedar

  # override on a per environment basis
  # legacy: bamboo-ree-1.8.7

config:
  # choose the configuration settings for all environments
  all:
    BUNDLE_WITHOUT: "test:development"
    RUBY_VERSION: ruby-1.9.3-p125
    PATH: "bin:vendor/bundle/ruby/1.9.1/bin:/usr/local/bin:/usr/bin:/bin"
    # CONFIG_VAR1: "config1"
    # CONFIG_VAR2: "config2"
  
  staging:
    RACK_ENV: staging
    RAILS_ENV: staging
  # you can also override configuration settings for each environment
  # production:
  #   CONFIG_VAR1: "config1-production"
  # staging:
  #   CONFIG_VAR1: "config1-staging"

collaborators:
  # Be sure to add yourself as a collaborator, otherwise your
  # access to the app will be revoked.
  all:
    - "cody@gunnertech.com"
    - "heroku@gunnertech.com"

domains:
  production:
    - "performantapp.com"
    - "www.performantapp.com"

addons:
  all:
    - custom_domains:basic
    - heroku-postgresql:dev
    - sendgrid:starter
    - scheduler:standard
    - cloudvertical:test
    - railsonfire:test
    - blitz:250

  production:
    
  staging:
    
