development:
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
  bucket: com.gunnertech.performance-unlimited.development
test:
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
  bucket: circlestreet-test
production:
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
  bucket: com.gunnertech.performance-unlimited.production
staging:
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
  bucket: com.gunnertech.performance-unlimited.staging