common: &common
  access_key_id: AKIAI67VTVS4637QSLEQA
  secret_access_key: 8SJg5B+ZT5De8WRgbKcWmvmgMjc0NxWnoKv6+e/z
  
development:
  <<: *common
  bucket: com.gunnertech.performance-unlimited.development
  
test:
  <<: *common
  bucket: circlestreet-test
  
production:
  <<: *common
  bucket: com.gunnertech.performance-unlimited.production
  
staging:
  bucket: com.gunnertech.performance-unlimited.staging