require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MetricTypesController do

  # This should return the minimal set of attributes required to create a valid
  # MetricType. As you add validations to MetricType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MetricTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all metric_types as @metric_types" do
      metric_type = MetricType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:metric_types).should eq([metric_type])
    end
  end

  describe "GET show" do
    it "assigns the requested metric_type as @metric_type" do
      metric_type = MetricType.create! valid_attributes
      get :show, {:id => metric_type.to_param}, valid_session
      assigns(:metric_type).should eq(metric_type)
    end
  end

  describe "GET new" do
    it "assigns a new metric_type as @metric_type" do
      get :new, {}, valid_session
      assigns(:metric_type).should be_a_new(MetricType)
    end
  end

  describe "GET edit" do
    it "assigns the requested metric_type as @metric_type" do
      metric_type = MetricType.create! valid_attributes
      get :edit, {:id => metric_type.to_param}, valid_session
      assigns(:metric_type).should eq(metric_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MetricType" do
        expect {
          post :create, {:metric_type => valid_attributes}, valid_session
        }.to change(MetricType, :count).by(1)
      end

      it "assigns a newly created metric_type as @metric_type" do
        post :create, {:metric_type => valid_attributes}, valid_session
        assigns(:metric_type).should be_a(MetricType)
        assigns(:metric_type).should be_persisted
      end

      it "redirects to the created metric_type" do
        post :create, {:metric_type => valid_attributes}, valid_session
        response.should redirect_to(MetricType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved metric_type as @metric_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        MetricType.any_instance.stub(:save).and_return(false)
        post :create, {:metric_type => {}}, valid_session
        assigns(:metric_type).should be_a_new(MetricType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MetricType.any_instance.stub(:save).and_return(false)
        post :create, {:metric_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested metric_type" do
        metric_type = MetricType.create! valid_attributes
        # Assuming there are no other metric_types in the database, this
        # specifies that the MetricType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MetricType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => metric_type.to_param, :metric_type => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested metric_type as @metric_type" do
        metric_type = MetricType.create! valid_attributes
        put :update, {:id => metric_type.to_param, :metric_type => valid_attributes}, valid_session
        assigns(:metric_type).should eq(metric_type)
      end

      it "redirects to the metric_type" do
        metric_type = MetricType.create! valid_attributes
        put :update, {:id => metric_type.to_param, :metric_type => valid_attributes}, valid_session
        response.should redirect_to(metric_type)
      end
    end

    describe "with invalid params" do
      it "assigns the metric_type as @metric_type" do
        metric_type = MetricType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MetricType.any_instance.stub(:save).and_return(false)
        put :update, {:id => metric_type.to_param, :metric_type => {}}, valid_session
        assigns(:metric_type).should eq(metric_type)
      end

      it "re-renders the 'edit' template" do
        metric_type = MetricType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MetricType.any_instance.stub(:save).and_return(false)
        put :update, {:id => metric_type.to_param, :metric_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested metric_type" do
      metric_type = MetricType.create! valid_attributes
      expect {
        delete :destroy, {:id => metric_type.to_param}, valid_session
      }.to change(MetricType, :count).by(-1)
    end

    it "redirects to the metric_types list" do
      metric_type = MetricType.create! valid_attributes
      delete :destroy, {:id => metric_type.to_param}, valid_session
      response.should redirect_to(metric_types_url)
    end
  end

end
