require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecordedMetricsController do

  # This should return the minimal set of attributes required to create a valid
  # RecordedMetric. As you add validations to RecordedMetric, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecordedMetricsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all recorded_metrics as @recorded_metrics" do
      recorded_metric = RecordedMetric.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recorded_metrics).should eq([recorded_metric])
    end
  end

  describe "GET show" do
    it "assigns the requested recorded_metric as @recorded_metric" do
      recorded_metric = RecordedMetric.create! valid_attributes
      get :show, {:id => recorded_metric.to_param}, valid_session
      assigns(:recorded_metric).should eq(recorded_metric)
    end
  end

  describe "GET new" do
    it "assigns a new recorded_metric as @recorded_metric" do
      get :new, {}, valid_session
      assigns(:recorded_metric).should be_a_new(RecordedMetric)
    end
  end

  describe "GET edit" do
    it "assigns the requested recorded_metric as @recorded_metric" do
      recorded_metric = RecordedMetric.create! valid_attributes
      get :edit, {:id => recorded_metric.to_param}, valid_session
      assigns(:recorded_metric).should eq(recorded_metric)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecordedMetric" do
        expect {
          post :create, {:recorded_metric => valid_attributes}, valid_session
        }.to change(RecordedMetric, :count).by(1)
      end

      it "assigns a newly created recorded_metric as @recorded_metric" do
        post :create, {:recorded_metric => valid_attributes}, valid_session
        assigns(:recorded_metric).should be_a(RecordedMetric)
        assigns(:recorded_metric).should be_persisted
      end

      it "redirects to the created recorded_metric" do
        post :create, {:recorded_metric => valid_attributes}, valid_session
        response.should redirect_to(RecordedMetric.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recorded_metric as @recorded_metric" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecordedMetric.any_instance.stub(:save).and_return(false)
        post :create, {:recorded_metric => {}}, valid_session
        assigns(:recorded_metric).should be_a_new(RecordedMetric)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecordedMetric.any_instance.stub(:save).and_return(false)
        post :create, {:recorded_metric => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recorded_metric" do
        recorded_metric = RecordedMetric.create! valid_attributes
        # Assuming there are no other recorded_metrics in the database, this
        # specifies that the RecordedMetric created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecordedMetric.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => recorded_metric.to_param, :recorded_metric => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested recorded_metric as @recorded_metric" do
        recorded_metric = RecordedMetric.create! valid_attributes
        put :update, {:id => recorded_metric.to_param, :recorded_metric => valid_attributes}, valid_session
        assigns(:recorded_metric).should eq(recorded_metric)
      end

      it "redirects to the recorded_metric" do
        recorded_metric = RecordedMetric.create! valid_attributes
        put :update, {:id => recorded_metric.to_param, :recorded_metric => valid_attributes}, valid_session
        response.should redirect_to(recorded_metric)
      end
    end

    describe "with invalid params" do
      it "assigns the recorded_metric as @recorded_metric" do
        recorded_metric = RecordedMetric.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecordedMetric.any_instance.stub(:save).and_return(false)
        put :update, {:id => recorded_metric.to_param, :recorded_metric => {}}, valid_session
        assigns(:recorded_metric).should eq(recorded_metric)
      end

      it "re-renders the 'edit' template" do
        recorded_metric = RecordedMetric.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecordedMetric.any_instance.stub(:save).and_return(false)
        put :update, {:id => recorded_metric.to_param, :recorded_metric => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recorded_metric" do
      recorded_metric = RecordedMetric.create! valid_attributes
      expect {
        delete :destroy, {:id => recorded_metric.to_param}, valid_session
      }.to change(RecordedMetric, :count).by(-1)
    end

    it "redirects to the recorded_metrics list" do
      recorded_metric = RecordedMetric.create! valid_attributes
      delete :destroy, {:id => recorded_metric.to_param}, valid_session
      response.should redirect_to(recorded_metrics_url)
    end
  end

end
