require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SelectedResponsesController do

  # This should return the minimal set of attributes required to create a valid
  # SelectedResponse. As you add validations to SelectedResponse, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SelectedResponsesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all selected_responses as @selected_responses" do
      selected_response = SelectedResponse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:selected_responses).should eq([selected_response])
    end
  end

  describe "GET show" do
    it "assigns the requested selected_response as @selected_response" do
      selected_response = SelectedResponse.create! valid_attributes
      get :show, {:id => selected_response.to_param}, valid_session
      assigns(:selected_response).should eq(selected_response)
    end
  end

  describe "GET new" do
    it "assigns a new selected_response as @selected_response" do
      get :new, {}, valid_session
      assigns(:selected_response).should be_a_new(SelectedResponse)
    end
  end

  describe "GET edit" do
    it "assigns the requested selected_response as @selected_response" do
      selected_response = SelectedResponse.create! valid_attributes
      get :edit, {:id => selected_response.to_param}, valid_session
      assigns(:selected_response).should eq(selected_response)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SelectedResponse" do
        expect {
          post :create, {:selected_response => valid_attributes}, valid_session
        }.to change(SelectedResponse, :count).by(1)
      end

      it "assigns a newly created selected_response as @selected_response" do
        post :create, {:selected_response => valid_attributes}, valid_session
        assigns(:selected_response).should be_a(SelectedResponse)
        assigns(:selected_response).should be_persisted
      end

      it "redirects to the created selected_response" do
        post :create, {:selected_response => valid_attributes}, valid_session
        response.should redirect_to(SelectedResponse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved selected_response as @selected_response" do
        # Trigger the behavior that occurs when invalid params are submitted
        SelectedResponse.any_instance.stub(:save).and_return(false)
        post :create, {:selected_response => {}}, valid_session
        assigns(:selected_response).should be_a_new(SelectedResponse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SelectedResponse.any_instance.stub(:save).and_return(false)
        post :create, {:selected_response => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested selected_response" do
        selected_response = SelectedResponse.create! valid_attributes
        # Assuming there are no other selected_responses in the database, this
        # specifies that the SelectedResponse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SelectedResponse.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => selected_response.to_param, :selected_response => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested selected_response as @selected_response" do
        selected_response = SelectedResponse.create! valid_attributes
        put :update, {:id => selected_response.to_param, :selected_response => valid_attributes}, valid_session
        assigns(:selected_response).should eq(selected_response)
      end

      it "redirects to the selected_response" do
        selected_response = SelectedResponse.create! valid_attributes
        put :update, {:id => selected_response.to_param, :selected_response => valid_attributes}, valid_session
        response.should redirect_to(selected_response)
      end
    end

    describe "with invalid params" do
      it "assigns the selected_response as @selected_response" do
        selected_response = SelectedResponse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SelectedResponse.any_instance.stub(:save).and_return(false)
        put :update, {:id => selected_response.to_param, :selected_response => {}}, valid_session
        assigns(:selected_response).should eq(selected_response)
      end

      it "re-renders the 'edit' template" do
        selected_response = SelectedResponse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SelectedResponse.any_instance.stub(:save).and_return(false)
        put :update, {:id => selected_response.to_param, :selected_response => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested selected_response" do
      selected_response = SelectedResponse.create! valid_attributes
      expect {
        delete :destroy, {:id => selected_response.to_param}, valid_session
      }.to change(SelectedResponse, :count).by(-1)
    end

    it "redirects to the selected_responses list" do
      selected_response = SelectedResponse.create! valid_attributes
      delete :destroy, {:id => selected_response.to_param}, valid_session
      response.should redirect_to(selected_responses_url)
    end
  end

end
